services:

  front:
    image: "wesleymime/aluraflix_front"
    restart: always
    ports:
      - "8080:3000"
    depends_on:
      - api

  api:
    image: "wesleymime/aluraflix_api"
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: aluraflix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

